spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userm?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
  aop:
    proxy-target-class:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
management:
  endpoints:
    web:
      exposure:
        include: ['httptrace', 'metrics']
my:
  shiro:
      # 后端免认证接口 url
      anonUrl: /login,/actuator/*,/captcha.jpg
      # token有效期，单位秒
      jwtTimeOut: 3600

server:
  port: 8081
